#!/usr/bin/env bash
set -e -x

unset BUNDLE_APP_CONFIG
export CUCUMBER_CORE_PATH=`readlink -f cucumber-core`

cd cucumber-master

ruby --version
bundle install -j8 --path vendor/cache --binstubs

export PATH=$PWD/bin:$PATH

rake
