groups:
  - name: cucumber
    jobs:
      - test

jobs:
  - name: test
    plan:
      - get: cucumber-master
        trigger: true
      - task: test-2.2
        file: cucumber-master/ci/test.yml
        config:
          image: docker:///ruby#2.2
      - task: test-2.1
        file: cucumber-master/ci/test.yml
        config:
          image: docker:///ruby#2.1

resources:
  - name: cucumber-master
    type: git
    source:
      branch: master
      uri: https://github.com/tom025/cucumber.git
